spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mail_managin_base?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true