app:
  baselink: http://127.0.0.1:8080/
db: # db properties
  #  driver: com.mysql.cj.jdbc.Driver
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mail_managin_base?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
  username: root
  password: root
#hibernate properties
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: create
