INSERT INTO domains VALUES (1, 'hneu.net', 'hneu.net', 'hneu.net');

INSERT INTO study_level VALUES (6, 6, 'Бакалавр');
INSERT INTO study_level VALUES (7, 7, '');
INSERT INTO study_level VALUES (8, 8, 'Магистр');

INSERT INTO faculty VALUES (1, 'КИМБ', 1, 'Консалтинга и международного бизнеса');
INSERT INTO faculty VALUES (2, 'ФФ', 2, 'Финансовый');
INSERT INTO faculty VALUES (3, 'МИМ', 3, 'Менеджмента и маркетинга');
INSERT INTO faculty VALUES (4, 'ЭИ', 4, 'Экономической Информатики');
INSERT INTO faculty VALUES (5, 'ЭП', 5, 'Экономики и права');
INSERT INTO faculty VALUES (6, 'МЭО', 6, 'Международных экономических отношений');
INSERT INTO faculty VALUES (7, 'ПИГ', 46, 'Подготовки иностраннх граждан');

INSERT INTO speciality VALUES (11, 'Освітні, педагогічні науки', 11);
INSERT INTO speciality VALUES (51, 'Економіка', 51);
INSERT INTO speciality VALUES (61, 'Журналістика', 61);
INSERT INTO speciality VALUES (71, 'Облік і оподаткування', 71);
INSERT INTO speciality VALUES (72, 'Фінанси, банківська справа та страхування', 72);
INSERT INTO speciality VALUES (73, 'Менеджмент', 73);
INSERT INTO speciality VALUES (75, 'Маркетинг', 75);
INSERT INTO speciality VALUES (76, 'Підприємництво, торгівля та біржова діяльність', 76);
INSERT INTO speciality VALUES (121, 'Інженерія програмного забезпечення', 121);
INSERT INTO speciality VALUES (122, 'Комп’ютерні науки', 122);
INSERT INTO speciality VALUES (126, 'Інформаційні системи та технології', 126);
INSERT INTO speciality VALUES (186, 'Видавництво та поліграфія', 186);
INSERT INTO speciality VALUES (242, 'Туризм', 242);
INSERT INTO speciality VALUES (281, 'Публічне управління та адміністрування', 281);
INSERT INTO speciality VALUES (291, 'Міжнародні відносини, суспільні комунікації та регіональні студії', 291);
INSERT INTO speciality VALUES (292, 'Міжнародні економічні відносини', 292);

INSERT INTO specialization VALUES (1, 'Педагогіка вищої школи', 1, 11);
INSERT INTO specialization VALUES (2, 'Економічна теорія та економічна політика', 1, 51);
INSERT INTO specialization VALUES (3, 'Економічна кібернетика', 2, 51);
INSERT INTO specialization VALUES (4, 'Економіка підприємства ', 6, 51);
INSERT INTO specialization VALUES (5, 'Економіка і організація агробізнесу', 7, 51);
INSERT INTO specialization VALUES (6, 'Економіка і правове забезпечення бізнесу', 8, 51);
INSERT INTO specialization VALUES (7, 'Управління персоналом та економіка праці', 9, 51);
INSERT INTO specialization VALUES (8, 'Бізнес-статистика і аналітика', 10, 51);
INSERT INTO specialization VALUES (9, 'Бізнес-аналітика та міжнародна статистика', 11, 51);
INSERT INTO specialization VALUES (10, 'Економіка та бізнес-моделювання', 12, 51);
INSERT INTO specialization VALUES (11, 'Міжнародна економіка', 13, 51);
INSERT INTO specialization VALUES (12, 'Управління нерухомістю', 14, 51);
INSERT INTO specialization VALUES (13, 'Аналіз даних у бізнес-економіці', 5, 51);
INSERT INTO specialization VALUES (14, 'Інформаційна економіка', 4, 51);
INSERT INTO specialization VALUES (15, 'Прикладна економіка', 3, 51);
INSERT INTO specialization VALUES (16, 'Реклама і зв’язки з громадськістю ', 1, 61);
INSERT INTO specialization VALUES (17, 'Медіа-комунікації', 2, 61);
INSERT INTO specialization VALUES (18, 'Облік і аудит', 1, 71);
INSERT INTO specialization VALUES (19, 'Оподаткування', 2, 71);
INSERT INTO specialization VALUES (20, 'Управління та адміністрування в сфері фінансів', 1, 72);
INSERT INTO specialization VALUES (21, 'Фінансові послуги', 2, 72);
INSERT INTO specialization VALUES (22, 'Банківська справа', 5, 72);
INSERT INTO specialization VALUES (23, 'Фінансовий менеджмент', 3, 72);
INSERT INTO specialization VALUES (24, 'Управління фінансовою діяльністю суб’єктів господарювання', 4, 72);
INSERT INTO specialization VALUES (25, 'Банківський менеджмент', 6, 72);
INSERT INTO specialization VALUES (26, 'Аналітика банківських процесів', 7, 72);
INSERT INTO specialization VALUES (27, 'Менеджмент організацій і адміністрування ', 1, 73);
INSERT INTO specialization VALUES (28, 'Менеджмент інноваційної діяльності', 2, 73);
INSERT INTO specialization VALUES (29, 'Менеджмент зовнішньоекономічної діяльності', 6, 73);
INSERT INTO specialization VALUES (30, 'Бізнес-адміністрування', 4, 73);
INSERT INTO specialization VALUES (31, 'Логістика', 3, 73);
INSERT INTO specialization VALUES (32, 'Адміністративний менеджмент', 5, 73);
INSERT INTO specialization VALUES (33, 'Управління фінансово-економічною безпекою', 7, 73);
INSERT INTO specialization VALUES (34, 'Управління проектами', 8, 73);
INSERT INTO specialization VALUES (35, 'Управління навчальним закладом ', 9, 73);
INSERT INTO specialization VALUES (36, 'Маркетинг', 1, 75);
INSERT INTO specialization VALUES (37, 'Підприємництво, торгівля та біржова діяльність', 1, 76);
INSERT INTO specialization VALUES (38, 'Інженерія програмного забезпечення', 1, 121);
INSERT INTO specialization VALUES (39, 'Інженерія програмного забезпечення Маг', 12, 121);
INSERT INTO specialization VALUES (40, 'Комп’ютерні науки', 1, 122);
INSERT INTO specialization VALUES (41, 'Комп’ютерні науки Маг', 12, 122);
INSERT INTO specialization VALUES (42, 'Комп’ютерний еколого-економічний моніторинг', 2, 122);
INSERT INTO specialization VALUES (43, 'Інформаційні системи та технології', 1, 126);
INSERT INTO specialization VALUES (44, 'Технології електронних мультимедійних видань', 1, 186);
INSERT INTO specialization VALUES (45, 'Комп’ютерні технології та системи видавничо-поліграфічних виробництв', 2, 186);
INSERT INTO specialization VALUES (46, 'Туризм', 1, 242);
INSERT INTO specialization VALUES (47, 'Публічне адміністрування', 1, 281);
INSERT INTO specialization VALUES (48, 'Державна служба', 2, 281);
INSERT INTO specialization VALUES (49, 'Міжнародні відносини, суспільні комунікації та регіональні студії', 1, 291);
INSERT INTO specialization VALUES (50, 'Міжнародний бізнес', 1, 292);